export enum ErrorMessages {
	EmailRequired = 'Email is required',
	InvalidEmail = 'Invalid email format',
	PasswordRequired = 'Password is required',
	PasswordMinLength = 'Add at least 4 characters long.',
	PasswordUppercase = 'Add at least one uppercase letter.',
	PasswordLowercase = 'Add at least one lowercase letter.',
	PasswordNumber = 'Add at least one number.',
	UsernameRequired = 'Username is required',
	UsernameMinLength = 'Username must be at least 3 characters long.',
	UsernameMaxLength = 'Username must be at most 20 characters long.',
	ConfirmPasswordRequired = 'Confirm password is required',
	PasswordsMustMatch = 'Passwords must match.',
	FirstNameRequired = 'First name is required.',
	FirstNameMaxLength = 'First name must not exceed 50 characters.',
	LastNameRequired = 'Last name is required.',
	LastNameMaxLength = 'Last name must not exceed 50 characters.',
	InvalidUrl = 'Invalid URL format.',
	GameNameRequired = 'Game name is required.',
	GameUrlRequired = 'Game URL is required.',
	GamesRequired = 'At least one game must be specified.',
	InvalidLanguage = 'Invalid language selected.',
	InvalidTheme = 'Invalid theme selected.',
	CreatedAtRequired = 'Creation date is required.',
	UpdatedAtRequired = 'Update date is required.',
	LastLoginRequired = 'Last login date is required.',
	IdRequired = 'Id is required.',
}
